# Crawling Twitter Data based on **Search Keyword** Using `tweet-harvest`

In [ ]:
# Import required Python package
!pip install pandas

# Install Node.js (because tweet-harvest built using Node.js)
!sudo apt-get update
!sudo apt-get install -y ca-certificates curl gnupg
!sudo mkdir -p /etc/apt/keyrings
!curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

!NODE_MAJOR=20 && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list

!sudo apt-get update
!sudo apt-get install nodejs -y

!node -v

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Get:1 https://cli.github.com/packages stable InRelease [3,917 B]
Get:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Get:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease [1,581 B]
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:5 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:6 https://cli.github.com/packages stable/main amd64 Packages [354 B]
Get:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:8 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages [2,696 kB]
Get:9 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:10 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [10.3 MB]
Get:11 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [7,090 kB]
Hit:12 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Get:13 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,297 kB]
Get:14 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [3,959 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Hit:16 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Get:17 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [4,309 kB]
Hit:18 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:19 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [7,394 kB]
Get:20 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,605 kB]
Get:21 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [3,030 kB]
Fetched 42.0 MB in 4s (10.5 MB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ca-certificates is already the newest version (20240203~22.04.1).
curl is already the newest version (7.81.0-1ubuntu1.24).
gnupg is already the newest version (2.2.27-3ubuntu2.5).
gnupg set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 57 not upgraded.
deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main
Hit:1 https://cli.github.com/packages stable InRelease
Hit:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Get:4 https://deb.nodesource.com/node_20.x nodistro InRelease [12.1 kB]
Hit:5 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:6 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Get:8 https://deb.nodesource.com/node_20.x nodistro/main amd64 Packages [14.7 kB]
Hit:9 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:10 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:11 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:12 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:13 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Fetched 26.8 kB in 1s (27.0 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  nodejs
0 upgraded, 1 newly installed, 0 to remove and 57 not upgraded.
Need to get 32.2 MB of archives.
After this operation, 196 MB of additional disk space will be used.
Get:1 https://deb.nodesource.com/node_20.x nodistro/main amd64 nodejs amd64 20.20.2-1nodesource1 [32.2 MB]
Fetched 32.2 MB in 1s (52.1 MB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package nodejs.
(Reading database ... 122402 files and directories currently installed.)
Preparing to unpack .../nodejs_20.20.2-1nodesource1_amd64.deb ...
Unpacking nodejs (20.20.2-1nodesource1) ...
Setting up nodejs (20.20.2-1nodesource1) ...
Processing triggers for man-db (2.10.2-1) ...
v20.20.2

In [ ]:
# Install dependencies yang missing
!sudo apt-get update
!sudo apt-get install -y \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libatspi2.0-0 \
    libxcomposite1 \
    libxdamage1 \
    libxrandr2 \
    libgbm-dev \
    libxkbcommon-dev \
    libasound2

# Install Playwright browsers
!npx playwright install-deps
!npx playwright install

Hit:1 https://cli.github.com/packages stable InRelease
Hit:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:4 https://deb.nodesource.com/node_20.x nodistro InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:6 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:8 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:9 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:10 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:11 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:12 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libxdamage1 is already the newest version (1:1.1.5-2build2).
libxdamage1 set to manually installed.
libxrandr2 is already the newest version (2:1.5.2-1build1).
libxrandr2 set to manually installed.
libasound2 is already the newest version (1.2.6.1-1ubuntu1.1).
libasound2 set to manually installed.
The following additional packages will be installed:
  at-spi2-core gsettings-desktop-schemas libatk1.0-data libxtst6
  session-migration
The following NEW packages will be installed:
  at-spi2-core gsettings-desktop-schemas libatk-bridge2.0-0 libatk1.0-0
  libatk1.0-data libatspi2.0-0 libgbm-dev libxcomposite1 libxkbcommon-dev
  libxtst6 session-migration
0 upgraded, 11 newly installed, 0 to remove and 57 not upgraded.
Need to get 383 kB of archives.
After this operation, 1,943 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatspi2.0-0 amd64 2.44.0-3 [80.9 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxtst6 amd64 2:1.2.3-1build4 [13.4 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 session-migration amd64 0.3.6 [9,774 B]
Get:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 gsettings-desktop-schemas all 42.0-1ubuntu1 [31.1 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 at-spi2-core amd64 2.44.0-3 [54.4 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk1.0-data all 2.36.0-3build1 [2,824 B]
Get:7 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk1.0-0 amd64 2.36.0-3build1 [51.9 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk-bridge2.0-0 amd64 2.38.0-3 [66.6 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgbm-dev amd64 23.2.1-1ubuntu3.1~22.04.3 [9,542 B]
Get:10 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcomposite1 amd64 1:0.4.5-1build2 [7,192 B]
Get:11 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxkbcommon-dev amd64 1.4.0-1 [54.9 kB]
Fetched 383 kB in 0s (2,992 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 11.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package libatspi2.0-0:amd64.
(Reading database ... 127765 files and directories currently installed.)
Preparing to unpack .../00-libatspi2.0-0_2.44.0-3_amd64.deb ...
Unpacking libatspi2.0-0:amd64 (2.44.0-3) ...
Selecting previously unselected package libxtst6:amd64.
Preparing to unpack .../01-libxtst6_2%3a1.2.3-1build4_amd64.deb ...
Unpacking libxtst6:amd64 (2:1.2.3-1build4) ...
Selecting previously unselected package session-migration.
Preparing to unpack .../02-session-migration_0.3.6_amd64.deb ...
Unpacking session-migration (0.3.6) ...
Selecting previously unselected package gsettings-desktop-schemas.
Preparing to unpack .../03-gsettings-desktop-schemas_42.0-1ubuntu1_all.deb ...
Unpacking gsettings-desktop-schemas (42.0-1ubuntu1) ...
Selecting previously unselected package at-spi2-core.
Preparing to unpack .../04-at-spi2-core_2.44.0-3_amd64.deb ...
Unpacking at-spi2-core (2.44.0-3) ...
Selecting previously unselected package libatk1.0-data.
Preparing to unpack .../05-libatk1.0-data_2.36.0-3build1_all.deb ...
Unpacking libatk1.0-data (2.36.0-3build1) ...
Selecting previously unselected package libatk1.0-0:amd64.
Preparing to unpack .../06-libatk1.0-0_2.36.0-3build1_amd64.deb ...
Unpacking libatk1.0-0:amd64 (2.36.0-3build1) ...
Selecting previously unselected package libatk-bridge2.0-0:amd64.
Preparing to unpack .../07-libatk-bridge2.0-0_2.38.0-3_amd64.deb ...
Unpacking libatk-bridge2.0-0:amd64 (2.38.0-3) ...
Selecting previously unselected package libgbm-dev:amd64.
Preparing to unpack .../08-libgbm-dev_23.2.1-1ubuntu3.1~22.04.3_amd64.deb ...
Unpacking libgbm-dev:amd64 (23.2.1-1ubuntu3.1~22.04.3) ...
Selecting previously unselected package libxcomposite1:amd64.
Preparing to unpack .../09-libxcomposite1_1%3a0.4.5-1build2_amd64.deb ...
Unpacking libxcomposite1:amd64 (1:0.4.5-1build2) ...
Selecting previously unselected package libxkbcommon-dev:amd64.
Preparing to unpack .../10-libxkbcommon-dev_1.4.0-1_amd64.deb ...
Unpacking libxkbcommon-dev:amd64 (1.4.0-1) ...
Setting up session-migration (0.3.6) ...
Created symlink /etc/systemd/user/graphical-session-pre.target.wants/session-migration.service → /usr/lib/systemd/user/session-migration.service.
Setting up libxtst6:amd64 (2:1.2.3-1build4) ...
Setting up libxkbcommon-dev:amd64 (1.4.0-1) ...
Setting up libatspi2.0-0:amd64 (2.44.0-3) ...
Setting up libgbm-dev:amd64 (23.2.1-1ubuntu3.1~22.04.3) ...
Setting up libatk1.0-data (2.36.0-3build1) ...
Setting up libatk1.0-0:amd64 (2.36.0-3build1) ...
Setting up libxcomposite1:amd64 (1:0.4.5-1build2) ...
Setting up gsettings-desktop-schemas (42.0-1ubuntu1) ...
Setting up libatk-bridge2.0-0:amd64 (2.38.0-3) ...
Processing triggers for libglib2.0-0:amd64 (2.72.4-0ubuntu2.9) ...
Processing triggers for libc-bin (2.35-0ubuntu3.8) ...
/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

Processing triggers for man-db (2.10.2-1) ...
Setting up at-spi2-core (2.44.0-3) ...
⠙⠹⠸⠼⠴⠦⠧⠇Need to install the following packages:
playwright@1.60.0
Ok to proceed? (y) y

⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦Installing dependencies...
Hit:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:2 https://cli.github.com/packages stable InRelease
Hit:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:4 https://deb.nodesource.com/node_20.x nodistro InRelease
Hit:5 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:6 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:7 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:8 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:9 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:10 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:11 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:12 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
fonts-liberation is already the newest version (1:1.07.4-11).
libatk-bridge2.0-0 is already the newest version (2.38.0-3).
libatk1.0-0 is already the newest version (2.36.0-3build1).
libatspi2.0-0 is already the newest version (2.44.0-3).
libegl1 is already the newest version (1.4.0-1).
libepoxy0 is already the newest version (1.5.10-1).
libepoxy0 set to manually installed.
libevent-2.1-7 is already the newest version (2.1.12-stable-1build3).
libevent-2.1-7 set to manually installed.
libfontconfig1 is already the newest version (2.13.1-4.2ubuntu5).
libgles2 is already the newest version (1.4.0-1).
libglx0 is already the newest version (1.4.0-1).
libglx0 set to manually installed.
libicu70 is already the newest version (70.1-2).
libicu70 set to manually installed.
libjpeg-turbo8 is already the newest version (2.1.2-0ubuntu1).
libjpeg-turbo8 set to manually installed.
libopengl0 is already the newest version (1.4.0-1).
libopus0 is already the newest version (1.3.1-0.1build2).
libopus0 set to manually installed.
libxcb-shm0 is already the newest version (1.14-3ubuntu3).
libxcb-shm0 set to manually installed.
libxcb1 is already the newest version (1.14-3ubuntu3).
libxcb1 set to manually installed.
libxcomposite1 is already the newest version (1:0.4.5-1build2).
libxcursor1 is already the newest version (1:1.2.0-2build4).
libxcursor1 set to manually installed.
libxdamage1 is already the newest version (1:1.1.5-2build2).
libxext6 is already the newest version (2:1.3.4-1build1).
libxfixes3 is already the newest version (1:6.0.0-1).
libxfixes3 set to manually installed.
libxi6 is already the newest version (2:1.8-1build1).
libxi6 set to manually installed.
libxkbcommon0 is already the newest version (1.4.0-1).
libxkbcommon0 set to manually installed.
libxrandr2 is already the newest version (2:1.5.2-1build1).
libxrender1 is already the newest version (1:0.9.10-1build4).
libxtst6 is already the newest version (2:1.2.3-1build4).
libxtst6 set to manually installed.
libx264-163 is already the newest version (2:0.163.3060+git5db6aa6-2build1).
libx264-163 set to manually installed.
libasound2 is already the newest version (1.2.6.1-1ubuntu1.1).
libatomic1 is already the newest version (12.3.0-1ubuntu1~22.04.3).
libatomic1 set to manually installed.
libcairo-gobject2 is already the newest version (1.16.0-5ubuntu2.1).
libcairo-gobject2 set to manually installed.
libcairo2 is already the newest version (1.16.0-5ubuntu2.1).
libcairo2 set to manually installed.
libcups2 is already the newest version (2.4.1op1-1ubuntu4.16).
libcups2 set to manually installed.
libdbus-1-3 is already the newest version (1.12.20-2ubuntu4.1).
libdbus-1-3 set to manually installed.
libdrm2 is already the newest version (2.4.113-2~ubuntu0.22.04.1).
libdrm2 set to manually installed.
libfreetype6 is already the newest version (2.11.1+dfsg-1ubuntu0.3).
libfreetype6 set to manually installed.
libgbm1 is already the newest version (23.2.1-1ubuntu3.1~22.04.3).
libgbm1 set to manually installed.
libgdk-pixbuf-2.0-0 is already the newest version (2.42.8+dfsg-1ubuntu0.5).
libgdk-pixbuf-2.0-0 set to manually installed.
libglib2.0-0 is already the newest version (2.72.4-0ubuntu2.9).
libgstreamer1.0-0 is already the newest version (1.20.3-0ubuntu1.1).
libgstreamer1.0-0 set to manually installed.
libgtk-4-1 is already the newest version (4.6.9+ds-0ubuntu0.22.04.2).
libgtk-4-1 set to manually installed.
libharfbuzz0b is already the newest version (2.7.4-1ubuntu3.2).
libharfbuzz0b set to manually installed.
liblcms2-2 is already the newest version (2.12~rc1-2ubuntu0.1).
liblcms2-2 set to manually installed.
libnspr4 is already the newest version (2:4.35-0ubuntu0.22.04.1).
libnspr4 set to manually installed.
libnss3 is already the newest version (2:3.98-0ubuntu0.22.04.3).
libnss3 set to manually installed.
libopenjp2-7 is already the newest version (2.4.0-6ubuntu0.5).
libopenjp2-7 set to manually installed.
libpango-1.0-0 is already the newest version (1.50.6+ds-2ubuntu1).
libpango-1.0-0 set to manually installed.
libpangocairo-1.0-0 is already the newest version (1.50.6+ds-2ubuntu1).
libpangocairo-1.0-0 set to manually installed.
libpng16-16 is already the newest version (1.6.37-3ubuntu0.5).
libpng16-16 set to manually installed.
libwayland-client0 is already the newest version (1.20.0-1ubuntu0.1).
libwayland-client0 set to manually installed.
libwayland-egl1 is already the newest version (1.20.0-1ubuntu0.1).
libwayland-egl1 set to manually installed.
libwayland-server0 is already the newest version (1.20.0-1ubuntu0.1).
libwayland-server0 set to manually installed.
libwebpdemux2 is already the newest version (1.2.2-2ubuntu0.22.04.2).
libx11-6 is already the newest version (2:1.7.5-1ubuntu0.3).
libx11-6 set to manually installed.
libx11-xcb1 is already the newest version (2:1.7.5-1ubuntu0.3).
libx11-xcb1 set to manually installed.
libxml2 is already the newest version (2.9.13+dfsg-1ubuntu0.11).
libxml2 set to manually installed.
libxslt1.1 is already the newest version (1.1.34-4ubuntu0.22.04.5).
ffmpeg is already the newest version (7:4.4.2-0ubuntu0.22.04.1).
xvfb is already the newest version (2:21.1.4-2ubuntu1.7~22.04.16).
The following additional packages will be installed:
  dictionaries-common glib-networking glib-networking-common
  glib-networking-services hunspell-en-us libaa1 libabsl20210324 libaspell15
  libcdparanoia0 libdca0 libdv4 libdvdnav4 libdvdread8 libfaad2 libfluidsynth3
  libfreeaptx0 libgav1-0 libgssdp-1.2-0 libgstreamer-plugins-bad1.0-0
  libgstreamer-plugins-good1.0-0 libgtk-3-common libgupnp-1.2-1
  libgupnp-igd-1.0-4 libhunspell-1.7-0 libilmbase25 libinstpatch-1.0-2
  libjson-glib-1.0-0 libjson-glib-1.0-common libkate1 libldacbt-enc2 libltc11
  libmjpegutils-2.1-0 libmodplug1 libmpcdec6 libmpeg2encpp-2.1-0
  libmplex2-2.1-0 libnice10 libopenexr25 libopenh264-6 libopenni2-0
  liborc-0.4-0 libqrencode4 libsbc1 libsecret-common libshout3 libsoundtouch1
  libsoup-3.0-common libsoup2.4-1 libsoup2.4-common libspandsp2 libsrtp2-1
  libtag1v5 libtag1v5-vanilla libtext-iconv-perl libv4l-0 libv4lconvert0
  libvisual-0.4-0 libvo-aacenc0 libvo-amrwbenc0 libwavpack1
  libwebrtc-audio-processing1 libwildmidi2 libyuv0 libzbar0 libzxingcore1
  timgm6mb-soundfont xfonts-encodings xfonts-utils
Suggested packages:
  ispell | aspell | hunspell wordlist frei0r-plugins gvfs hunspell
  openoffice.org-hunspell | openoffice.org-core aspell libdv-bin oss-compat
  libdvdcss2 libenchant-2-voikko libvisual-0.4-plugins gnome-shell
  | notification-daemon libwildmidi-config fluid-soundfont-gm
Recommended packages:
  fonts-ipafont-mincho fonts-tlwg-loma gstreamer1.0-x aspell-en
  | aspell-dictionary | aspell6a-dictionary enchant-2 gstreamer1.0-gl
  libgtk-3-bin librsvg2-common libmagickcore-6.q16-6-extra
The following NEW packages will be installed:
  dictionaries-common fonts-freefont-ttf fonts-ipafont-gothic
  fonts-noto-color-emoji fonts-tlwg-loma-otf fonts-unifont fonts-wqy-zenhei
  glib-networking glib-networking-common glib-networking-services
  gstreamer1.0-libav gstreamer1.0-plugins-bad gstreamer1.0-plugins-base
  gstreamer1.0-plugins-good hunspell-en-us libaa1 libabsl20210324 libaspell15
  libavif13 libcdparanoia0 libdbus-glib-1-2 libdca0 libdv4 libdvdnav4
  libdvdread8 libenchant-2-2 libevdev2 libfaad2 libffi7 libfluidsynth3
  libfreeaptx0 libgav1-0 libgssdp-1.2-0 libgstreamer-gl1.0-0
  libgstreamer-plugins-bad1.0-0 libgstreamer-plugins-base1.0-0
  libgstreamer-plugins-good1.0-0 libgtk-3-0 libgtk-3-common libgudev-1.0-0
  libgupnp-1.2-1 libgupnp-igd-1.0-4 libharfbuzz-icu0 libhunspell-1.7-0
  libhyphen0 libilmbase25 libinstpatch-1.0-2 libjson-glib-1.0-0
  libjson-glib-1.0-common libkate1 libldacbt-enc2 libltc11 libmanette-0.2-0
  libmjpegutils-2.1-0 libmodplug1 libmpcdec6 libmpeg2encpp-2.1-0
  libmplex2-2.1-0 libnice10 libnotify4 libopenexr25 libopenh264-6 libopenni2-0
  liborc-0.4-0 libproxy1v5 libqrencode4 libsbc1 libsecret-1-0 libsecret-common
  libshout3 libsoundtouch1 libsoup-3.0-0 libsoup-3.0-common libsoup2.4-1
  libsoup2.4-common libspandsp2 libsrtp2-1 libtag1v5 libtag1v5-vanilla
  libtext-iconv-perl libv4l-0 libv4lconvert0 libvisual-0.4-0 libvo-aacenc0
  libvo-amrwbenc0 libwavpack1 libwebrtc-audio-processing1 libwildmidi2
  libwoff1 libyuv0 libzbar0 libzxingcore1 timgm6mb-soundfont xfonts-cyrillic
  xfonts-encodings xfonts-scalable xfonts-utils
0 upgraded, 97 newly installed, 0 to remove and 57 not upgraded.
Need to get 53.4 MB of archives.
After this operation, 141 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 fonts-ipafont-gothic all 00303-21ubuntu1 [3,513 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 libtext-iconv-perl amd64 1.7-7build3 [14.3 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 dictionaries-common all 1.28.14 [185 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 fonts-freefont-ttf all 20120503-10build1 [2,388 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 fonts-noto-color-emoji all 2.047-0ubuntu0.22.04.1 [10.0 MB]
Get:6 http://archive.ubuntu.com/ubuntu jammy/universe amd64 fonts-tlwg-loma-otf all 1:0.7.3-1 [107 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy/universe amd64 fonts-unifont all 1:14.0.01-1 [3,551 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy/universe amd64 fonts-wqy-zenhei all 0.9.45-8 [7,472 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy/main amd64 libproxy1v5 amd64 0.4.17-2 [51.9 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy/main amd64 glib-networking-common all 2.72.0-1 [3,718 B]
Get:11 http://archive.ubuntu.com/ubuntu jammy/main amd64 glib-networking-services amd64 2.72.0-1 [9,982 B]
Get:12 http://archive.ubuntu.com/ubuntu jammy/main amd64 glib-networking amd64 2.72.0-1 [69.8 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 liborc-0.4-0 amd64 1:0.4.32-2ubuntu0.1 [228 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgstreamer-plugins-base1.0-0 amd64 1.20.1-1ubuntu0.6 [848 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 gstreamer1.0-libav amd64 1.20.3-0ubuntu1 [103 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy/main amd64 libcdparanoia0 amd64 3.10.2+debian-14build2 [49.3 kB]
Get:17 http://archive.ubuntu.com/ubuntu jammy/main amd64 libvisual-0.4-0 amd64 0.4.0-17build2 [108 kB]
Get:18 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 gstreamer1.0-plugins-base amd64 1.20.1-1ubuntu0.6 [712 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy/main amd64 libaa1 amd64 1.4p5-50build1 [51.9 kB]
Get:20 http://archive.ubuntu.com/ubuntu jammy/main amd64 libdv4 amd64 1.0.0-14build1 [61.9 kB]
Get:21 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgstreamer-plugins-good1.0-0 amd64 1.20.3-0ubuntu1.6 [30.4 kB]
Get:22 http://archive.ubuntu.com/ubuntu jammy/main amd64 libgudev-1.0-0 amd64 1:237-2build1 [16.3 kB]
Get:23 http://archive.ubuntu.com/ubuntu jammy/main amd64 libshout3 amd64 2.4.5-1build3 [54.5 kB]
Get:24 http://archive.ubuntu.com/ubuntu jammy/main amd64 libtag1v5-vanilla amd64 1.11.1+dfsg.1-3ubuntu3 [304 kB]

In [ ]:
token = '78cedf56ad0373d932b27a03c3f76312ae6ab8d9'

In [ ]:
# Crawl Data

filename = 'TKA.csv'
search_keyword = 'TKA  since:2025-12-25 until:2025-12-26 lang:in'
limit = 1000

!npx --yes tweet-harvest@latest -o "{filename}" -s "{search_keyword}" -l {limit} --token "{token}"

⠙⠹⠸⠼Tweet Harvest [v2.7.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


Found existing file ./tweets-data/TKA.csv, renaming to ./tweets-data/TKA.old.csv

-- Scrolling... (1)
Filling in keywords: TKA  since:2025-12-25 until:2025-12-26 lang:in

 (2) (3)

Your tweets saved to: /content/tweets-data/TKA.csv
Total tweets saved: 20

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/TKA.csv
Total tweets saved: 40

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/TKA.csv
Total tweets saved: 60

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/TKA.csv
Total tweets saved: 80

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/TKA.csv
Total tweets saved: 100

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/TKA.csv
Total tweets saved: 120

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/TKA.csv
Total tweets saved: 129

-- Scrolling... (1)[v2.7.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...

-- Scrolling... (1)[v2.7.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...
[v2.7.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...

-- Scrolling... (1)[v2.7.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 129 tweets, done scrolling...
⠙

In [ ]:
import pandas as pd

# Specify the path to your CSV file
file_path = f"tweets-data/TKA.csv"

# Read the CSV file into a pandas DataFrame
df = pd.read_csv(file_path)

In [ ]:
# Crawl Data

filename = 'TKA2.csv'
search_keyword = 'TKA since:2025-12-26 until:2025-12-27 lang:in'
limit = 1000

!npx --yes tweet-harvest@latest -o "{filename}" -s "{search_keyword}" -l {limit} --token "{token}"

⠙⠹⠸⠼⠴Tweet Harvest [v2.7.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


Found existing file ./tweets-data/TKA2.csv, renaming to ./tweets-data/TKA2.old.csv

-- Scrolling... (1)
Filling in keywords: TKA since:2025-12-26 until:2025-12-27 lang:in

 (2) (3) (4)

Your tweets saved to: /content/tweets-data/TKA2.csv
Total tweets saved: 20

-- Scrolling... (1) (2) (3)

Your tweets saved to: /content/tweets-data/TKA2.csv
Total tweets saved: 40

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/TKA2.csv
Total tweets saved: 60

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/TKA2.csv
Total tweets saved: 80

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/TKA2.csv
Total tweets saved: 100

-- Scrolling... (1) (2) (3)

Your tweets saved to: /content/tweets-data/TKA2.csv
Total tweets saved: 114

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1)[v2.7.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...
[v2.7.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...
[v2.7.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...

-- Scrolling... (1)[v2.7.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 114 tweets, done scrolling...
⠙

In [ ]:
import pandas as pd

# Specify the path to your CSV file
file_path2 = f"tweets-data/TKA2.csv"

# Read the CSV file into a pandas DataFrame
df2 = pd.read_csv(file_path2)

In [ ]:
# Crawl Data

filename = 'TKA3.csv'
search_keyword = 'TKA since:2025-12-27 until:2025-12-28 lang:in'
limit = 1000

!npx --yes tweet-harvest@latest -o "{filename}" -s "{search_keyword}" -l {limit} --token "{token}"

⠙⠹⠸⠼⠴⠦⠧Tweet Harvest [v2.7.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


Found existing file ./tweets-data/TKA3.csv, renaming to ./tweets-data/TKA3.old.csv

-- Scrolling... (1)
Filling in keywords: TKA since:2025-12-27 until:2025-12-28 lang:in

 (2) (3) (4)

Your tweets saved to: /content/tweets-data/TKA3.csv
Total tweets saved: 20

-- Scrolling... (1) (2) (3) (4)

Your tweets saved to: /content/tweets-data/TKA3.csv
Total tweets saved: 40

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/TKA3.csv
Total tweets saved: 60

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/TKA3.csv
Total tweets saved: 80

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/TKA3.csv
Total tweets saved: 100

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/TKA3.csv
Total tweets saved: 112

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1)[v2.7.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...
[v2.7.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...

-- Scrolling... (1)[v2.7.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...
[v2.7.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 112 tweets, done scrolling...
⠙

In [ ]:
# Specify the path to your CSV file
file_path3 = f"tweets-data/TKA3.csv"

# Read the CSV file into a pandas DataFrame
df3 = pd.read_csv(file_path3)

In [ ]:
# Crawl Data

filename = 'TKA4.csv'
search_keyword = 'TKA stres since:2025-07-28 until:2025-12-29 lang:in'
limit = 1000

!npx --yes tweet-harvest@latest -o "{filename}" -s "{search_keyword}" -l {limit} --token "{token}"

⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋npm warn deprecated glob@7.2.3: Old versions of glob are not supported, and contain widely publicized security vulnerabilities, which have been fixed in the current version. Please update. Support for old versions may be purchased (at exorbitant rates) by contacting i@izs.me
⠋npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
⠙npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
⠙npm warn deprecated @playwright/test@1.41.1: Please update to the latest version of Playwright to test up-to-date browsers.
⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸Tweet Harvest [v2.7.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1)
Filling in keywords: TKA stres since:2025-07-28 until:2025-12-29 lang:in

 (2) (3) (4)Created new directory: /content/tweets-data


Your tweets saved to: /content/tweets-data/TKA4.csv
Total tweets saved: 20

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/TKA4.csv
Total tweets saved: 40

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/TKA4.csv
Total tweets saved: 60

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/TKA4.csv
Total tweets saved: 66
[v2.7.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...

-- Scrolling... (1)[v2.7.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...
[v2.7.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...

-- Scrolling... (1)[v2.7.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 66 tweets, done scrolling...
⠙

In [ ]:
import pandas as pd
file_path4 = f"tweets-data/TKA4.csv"
df4 = pd.read_csv(file_path4)
df4

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1977006083102421494,2025-10-11T13:39:15.000Z,1,"my #progress, agak stres dikit tapi asiek ea.....",1977006083102421494,https://pbs.twimg.com/media/G2-8izBbwAkfTPx.jpg,NaN,in,NaN,0,0,0,https://x.com/kyllarthr/status/197700608310242...,1520235150109736960,kyllarthr
1,1984998781256155205,2025-11-02T14:59:23.000Z,0,"stres TKA pdhl aing blon belajar, anjing",1984998781256155205,NaN,NaN,in,NaN,0,0,0,https://x.com/iniiirennnn/status/1984998781256...,1959571512589217792,iniiirennnn
2,1985418740759241049,2025-11-03T18:48:09.000Z,1,Gw ketika melihat adik² stres TKA/UN https://t...,1985418740759241049,https://pbs.twimg.com/media/G42f0thbQAgcFnm.jpg,NaN,in,NaN,0,0,0,https://x.com/priadibumi/status/19854187407592...,756753916650323968,priadibumi
3,1993266076378186144,2025-11-25T10:30:40.000Z,3,Kuusahain buat dateng STS kamu yak\n\nTerima k...,1993266076378186144,https://pbs.twimg.com/media/G6mA7atacAAv_J8.jpg,NaN,in,NaN,0,2,1,https://x.com/SyahalMaulana15/status/199326607...,1689941556533547008,SyahalMaulana15
4,1985059661280899143,2025-11-02T19:01:18.000Z,1,h-3 muntah pas mlm badan anget tka pls lo udh ...,1985059661280899143,NaN,NaN,in,NaN,0,1,0,https://x.com/lovchocomilk/status/198505966128...,1541230353473347585,lovchocomilk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,1985196318621589643,2025-11-03T04:04:20.000Z,0,"""masa tka stres"" LAH?? 😂😂😂",1985196318621589643,NaN,NaN,in,NaN,0,0,0,https://x.com/seobiescuit/status/1985196318621...,1485586717910646787,seobiescuit
62,1975231716727087588,2025-10-06T16:08:33.000Z,0,efek samping stres tka,1975231716727087588,NaN,NaN,in,NaN,0,0,0,https://x.com/ttesfayye/status/197523171672708...,1773933679557111808,ttesfayye
63,1992255892071596513,2025-11-22T15:36:33.000Z,11,Jadi pemerintah kok nggak pernah muhasabah. Gu...,1992255892071596513,NaN,NaN,in,NaN,0,0,4,https://x.com/iniaesha/status/1992255892071596513,1282577444663222274,iniaesha
64,1983732061543526447,2025-10-30T03:05:54.000Z,30,"abis tka aku mau beli buku fiksi, kira kira ap...",1983732061543526447,https://pbs.twimg.com/media/G4ehvi-a8AIAX3j.jpg,NaN,in,NaN,0,19,0,https://x.com/akuamma_/status/1983732061543526447,1445272240912678915,akuamma_
65,1980857367337279870,2025-10-22T04:42:53.000Z,1,stres hafalan mandarin + tryout TKA 🫩,1980857367337279870,NaN,NaN,in,NaN,0,2,0,https://x.com/kkumeuongi/status/19808573673372...,1909792939666292736,kkumeuongi

In [ ]:
# Crawl Data

filename = 'TKA5.csv'
search_keyword = 'TKA since:2025-12-29 until:2026-01-05 lang:in'
limit = 1000

!npx --yes tweet-harvest@latest -o "{filename}" -s "{search_keyword}" -l {limit} --token "{token}"

⠙⠹⠸⠼⠴Tweet Harvest [v2.7.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


Found existing file ./tweets-data/TKA5.csv, renaming to ./tweets-data/TKA5.old.csv

-- Scrolling... (1)
Filling in keywords: TKA since:2025-12-29 until:2026-01-05 lang:in

 (2) (3)

Your tweets saved to: /content/tweets-data/TKA5.csv
Total tweets saved: 20

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/TKA5.csv
Total tweets saved: 40

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/TKA5.csv
Total tweets saved: 60

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/TKA5.csv
Total tweets saved: 80

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/TKA5.csv
Total tweets saved: 100

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/TKA5.csv
Total tweets saved: 120

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/TKA5.csv
Total tweets saved: 138

-- Scrolling... (1)[v2.7.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...

-- Scrolling... (1)[v2.7.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...

-- Scrolling... (1)[v2.7.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...

-- Scrolling... (1)[v2.7.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 138 tweets, done scrolling...
⠙

In [ ]:
file_path5 = f"tweets-data/TKA5.csv"
df5 = pd.read_csv(file_path5)

In [ ]:
# Gabungkan seluruh df
# dfa = pd.read_csv(f"dataset_tka.csv")
df_combined = pd.concat([df, df2, df3,df4, df5], ignore_index=True)

print(f"Data pertama: {len(df)} rows")
print(f"Data kedua: {len(df2)} rows")
print(f"Data ketiga: {len(df3)} rows")
print(f"Data ke4: {len(df4)} rows")
print(f"Data ke5: {len(df5)} rows")
print(f"Data gabungan: {len(df_combined)} rows")
display(df_combined.head())

Data pertama: 129 rows
Data kedua: 114 rows
Data ketiga: 112 rows
Data ke4: 140 rows
Data ke5: 138 rows
Data gabungan: 633 rows

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,2004180355738194293,2025-12-25T13:20:07.000Z,310,sch! ngeliat nilai rata-rata nasional yg jeblo...,2004180355738194293,NaN,NaN,in,NaN,2,11,4,https://x.com/schfess/status/2004180355738194293,1201673806156161025,schfess
1,2004006706125078693,2025-12-25T01:50:06.000Z,3,Ptn! TKA kemaren aku ngambil kimia biologi di ...,2004006706125078693,NaN,NaN,in,NaN,0,5,0,https://x.com/sbmptnfess/status/20040067061250...,1205629250423779328,sbmptnfess
2,2004288566843576733,2025-12-25T20:30:06.000Z,1,PTN! denger denger tka gajadi buat snbp 😔 http...,2004288566843576733,https://pbs.twimg.com/media/G9Cp1IqWYAAGRb8.png,NaN,in,NaN,0,3,0,https://x.com/sbmptnfess/status/20042885668435...,1205629250423779328,sbmptnfess
3,2004174160394907801,2025-12-25T12:55:30.000Z,0,mnrt gua jg tka gaakan keluar besok jir org ga...,2004174160394907801,NaN,NaN,in,NaN,0,1,0,https://x.com/pirprott/status/2004174160394907801,1631137282140049411,pirprott
4,2004178245085024581,2025-12-25T13:11:44.000Z,7,"Guru TU gua aja penasaran sama hasilnya, apala...",2004178245085024581,https://pbs.twimg.com/media/G9BFfWTb0AQIhGU.jpg,NaN,in,NaN,0,4,2,https://x.com/Majidun_Staners/status/200417824...,1902523848110804992,Majidun_Staners

In [ ]:
# Hapus duplikat berdasarkan kolom 'id' (jika ada)
if 'id' in df_combined.columns:
    df_combined = df_combined.drop_duplicates(subset=['id'])
    print(f"Setelah hapus duplikat: {len(df_combined)} rows")
else:
    # Jika tidak ada kolom 'id', hapus duplikat berdasarkan semua kolom
    df_combined = df_combined.drop_duplicates()
    print(f"Setelah hapus duplikat: {len(df_combined)} rows")

display(df_combined)

Setelah hapus duplikat: 633 rows

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,2004180355738194293,2025-12-25T13:20:07.000Z,310,sch! ngeliat nilai rata-rata nasional yg jeblo...,2004180355738194293,NaN,NaN,in,NaN,2,11,4,https://x.com/schfess/status/2004180355738194293,1201673806156161025,schfess
1,2004006706125078693,2025-12-25T01:50:06.000Z,3,Ptn! TKA kemaren aku ngambil kimia biologi di ...,2004006706125078693,NaN,NaN,in,NaN,0,5,0,https://x.com/sbmptnfess/status/20040067061250...,1205629250423779328,sbmptnfess
2,2004288566843576733,2025-12-25T20:30:06.000Z,1,PTN! denger denger tka gajadi buat snbp 😔 http...,2004288566843576733,https://pbs.twimg.com/media/G9Cp1IqWYAAGRb8.png,NaN,in,NaN,0,3,0,https://x.com/sbmptnfess/status/20042885668435...,1205629250423779328,sbmptnfess
3,2004174160394907801,2025-12-25T12:55:30.000Z,0,mnrt gua jg tka gaakan keluar besok jir org ga...,2004174160394907801,NaN,NaN,in,NaN,0,1,0,https://x.com/pirprott/status/2004174160394907801,1631137282140049411,pirprott
4,2004178245085024581,2025-12-25T13:11:44.000Z,7,"Guru TU gua aja penasaran sama hasilnya, apala...",2004178245085024581,https://pbs.twimg.com/media/G9BFfWTb0AQIhGU.jpg,NaN,in,NaN,0,4,2,https://x.com/Majidun_Staners/status/200417824...,1902523848110804992,Majidun_Staners
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
628,2007178581320053230,2026-01-02T19:54:00.000Z,0,"astagaa, kasian bgtt :'(((, cuma beda 2 tahun ...",2007178581320053230,NaN,NaN,in,NaN,0,0,0,https://x.com/caaomei/status/2007178581320053230,1544365338921295874,caaomei
629,2007429742795075606,2026-01-03T12:32:01.000Z,1,Alhamdulillah.. Tes Kemampuan Akademik (TKA) T...,2007429742795075606,https://pbs.twimg.com/media/G9vSU8tbgAAJEaZ.jpg,NaN,in,NaN,0,0,1,https://x.com/ibnuabbasklaten/status/200742974...,2925303030,ibnuabbasklaten
630,2007644647603261670,2026-01-04T02:45:58.000Z,0,TKA tingkat SMA anjlok. \n\nTKA Siapa Takut? L...,2007644647603261670,NaN,NaN,in,NaN,0,0,0,https://x.com/_shab_7/status/2007644647603261670,1873835924,_shab_7
631,2007317892023595297,2026-01-03T05:07:34.000Z,0,"NGAKAK LIAT PUNYAKU, that ""screen time lebih b...",2007317892023595297,https://pbs.twimg.com/media/G9ts_ApbAAAv4CM.jpg,NaN,in,NaN,0,1,0,https://x.com/auriemaw/status/2007317892023595297,1568861278004981760,auriemaw
632,2007276816105648437,2026-01-03T02:24:21.000Z,0,nilai TKA babi😃🙃,2007276816105648437,NaN,NaN,in,NaN,0,0,0,https://x.com/ccookiechoco/status/200727681610...,1501479735624290309,ccookiechoco

In [ ]:
df_combined = df_combined[df_combined['lang'] == 'in']

In [ ]:
combined_filename = "TKA_sabtu 13.csv"
df_combined.to_csv(f"tweets-data/{combined_filename}", index=False)

print(f"Data gabungan disimpan sebagai: {combined_filename}")
print(f"Total data: {len(df_combined)} tweets")

Data gabungan disimpan sebagai: TKA_sabtu 13.csv
Total data: 633 tweets

In [ ]:
dfa = pd.read_csv(f"TKA_sabtu 1.csv")
dfb = pd.read_csv(f"TKA_sabtu 2.csv")
dfc = pd.read_csv(f"TKA_sabtu 3.csv")
dfd = pd.read_csv(f"TKA_sabtu 4.csv")
dfe = pd.read_csv(f"TKA_sabtu 5.csv")
dff = pd.read_csv(f"TKA_sabtu 6.csv")
dfg = pd.read_csv(f"TKA_sabtu 7.csv")
dfh = pd.read_csv(f"TKA_sabtu 8.csv")
dfi = pd.read_csv(f"TKA_sabtu 9.csv")
dfj = pd.read_csv(f"TKA_sabtu 10.csv")
dfk = pd.read_csv(f"TKA_sabtu 11.csv")
dfl = pd.read_csv(f"TKA_sabtu 12.csv")
dfm = pd.read_csv(f"TKA_sabtu 13.csv")
dfn = pd.read_csv(f"dataset_tka.csv")

In [ ]:
list_df = [dfa, dfb, dfc, dfd, dfe, dff, dfg, dfh, dfi, dfj, dfk, dfl, dfm, dfn]
df = pd.concat(list_df, ignore_index=True)

## analisis awal

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv(f"dataset_tka (1).csv")

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4465 entries, 0 to 4464
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   conversation_id_str      4465 non-null   float64
 1   created_at               4465 non-null   object
 2   favorite_count           4465 non-null   int64
 3   full_text                4465 non-null   object
 4   id_str                   4465 non-null   float64
 5   image_url                0 non-null      float64
 6   in_reply_to_screen_name  164 non-null    object
 7   lang                     4465 non-null   object
 8   location                 0 non-null      float64
 9   quote_count              4465 non-null   int64
 10  reply_count              4465 non-null   int64
 11  retweet_count            4465 non-null   int64
 12  tweet_url                4465 non-null   object
 13  user_id_str              4465 non-null   float64
 14  username                 4465 non-null   object
dtypes: float64(5), int64(4), object(6)
memory usage: 523.4+ KB

In [ ]:
df = df.drop_duplicates(subset=['full_text'])
df = df.dropna(subset=['full_text'])
df.reset_index(drop=True, inplace=True)
print("Jumlah data setelah hapus duplikat:", len(df))
display(df)

Jumlah data setelah hapus duplikat: 4465

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1.930000e+18,2025-06-15T13:36:00.000Z,128,Sch! Guys aku ada grup belajar buat angkatan 2...,1.930000e+18,NaN,NaN,in,NaN,1,249,8,https://x.com/schfess/status/1934243496950632754,1.200000e+18,schfess
1,1.930000e+18,2025-06-16T10:01:07.000Z,31,sch! guys aku ada grup belajar buat angkatan 2...,1.930000e+18,NaN,NaN,in,NaN,0,80,0,https://x.com/schfess/status/1934551807960990030,1.200000e+18,schfess
2,1.930000e+18,2025-06-17T00:11:41.000Z,36,Semoga mental ku sebagai akt 26 ini kuat mengh...,1.930000e+18,NaN,NaN,in,NaN,0,2,7,https://x.com/kejaaanaaa/status/19347658565355...,1.770000e+18,kejaaanaaa
3,1.940000e+18,2025-06-17T22:45:05.000Z,0,stud! aku ada rekomendasi grup ambis nih buat ...,1.940000e+18,NaN,NaN,in,NaN,0,0,0,https://x.com/snbtfess/status/1935106452164677866,1.520000e+18,snbtfess
4,1.930000e+18,2025-06-17T05:30:36.000Z,0,Tka kok 9 hari dah kan tesnya 5 doang,1.930000e+18,NaN,NaN,in,NaN,0,2,0,https://x.com/kejaaanaaa/status/19348461166649...,1.770000e+18,kejaaanaaa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4460,1.990000e+18,2025-11-26T10:56:44.000Z,0,besok PAS statistika tapii soal soal tka (gug...,1.990000e+18,NaN,NaN,in,NaN,0,0,0,https://x.com/lovebrawijaya/status/19936350227...,1.780000e+18,lovebrawijaya
4461,1.990000e+18,2025-11-24T09:04:51.000Z,0,abis gladi ASAS dan wow wkwk soal soalnya miri...,1.990000e+18,NaN,NaN,in,NaN,0,1,0,https://x.com/lownJgf/status/1992882092368429528,1.630000e+18,lownJgf
4462,1.990000e+18,2025-11-10T11:39:14.000Z,0,guruku nyuruh nulis kembali 10 soal tka b indo...,1.990000e+18,NaN,NaN,in,NaN,0,0,0,https://x.com/byoviewer/status/198784751563147...,1.490000e+18,byoviewer
4463,2.000000e+18,2025-12-01T12:39:47.000Z,0,UAS bindo ku pake soal tka bejir,2.000000e+18,NaN,NaN,in,NaN,0,0,0,https://x.com/taes_noo/status/1995472899310829824,1.880000e+18,taes_noo
4464,1.990000e+18,2025-11-05T01:35:00.000Z,0,Ada yang punya bocoran soal tka kimia ga? ptn!,1.990000e+18,NaN,NaN,in,NaN,0,1,0,https://x.com/sbmptnfess/status/19858835144963...,1.210000e+18,sbmptnfess

In [ ]:
# Membuat dataframe sementara berisi data yang TIDAK mengandung 'TKA'
df_dropped = df[~df['full_text'].str.contains('TKA' , case=False, na=False)]

# Menampilkan data yang akan dibuang
print(f"Jumlah data yang akan di-drop: {len(df_dropped)} baris")
display(df_dropped[['username', 'full_text']].head(70)) # Melihat 20 sampel teratas

Jumlah data yang akan di-drop: 161 baris

             username                                          full_text
22       motherlander  Semoga yang suka mengintimidasi dan meretas hi...
54    theyycallmebass                 Sampe salah fokus kamera gueee!! 😭
73    theyycallmebass          Loh yang penting kan KOOPERATIF dongggggg
147   theyycallmebass           Yah ketololan SMESCO lagi ini mah wkwkwk
160   theyycallmebass  Sori bgt jadi terkesan mempermasalahkan hal re...
...               ...                                                ...
1910     Anaxagoras_s  Kemaleman kayaknya deh (((^_^;) but yang masih...
1949  theyycallmebass               Sori sori aje nih bos @L_MarshaJKT48
2006     Anaxagoras_s   TIFOSI BERSINAR!!\nbentar mau nyiapin jj buat sw
2092     Anaxagoras_s                   Mbb ya kakk! Terimakasih banyakk
2131  theyycallmebass  Duluan w ngantuk besop masih ngangstor. Jan ga...

[70 rows x 2 columns]

In [ ]:
import re
promo = [
    "harga", "tryout", "bimbel", "les", "kelas gratis",
    "daftar sekarang", "diskon", "promo", "open kelas",
    "pendaftaran", "link di bio", "hubungi", "wa",
    "wts","wtb","garansi","pricelist",
    "whatsapp", "t.me", "telegram", "zoom class",
    "ruangguru", "zenius", "brain academy",
    "kode promo", "tutor", "privat", "booking",
    "join kelas", "kelas intensif", "ebook gratis",
    "jualan", "open jasa", "admin", "slot terbatas",
    "detik", "kompas", "cnn", "tribun", "tempo",
    "liputan6", "kumparan", "tvone", "metrotv", "china",
    "pemerintah","pemimpin","dzalim","akbar","prabowo",
    "asing","kritik", "jokowi", "tirto","pejabat","antek",
    "asing","stafsus", "korupsi", "kpk","kemnaker","disnaker",
    "disnakertrans","menaker","menakertrans","imigrasi","visa",
    "pemerasan","tersangka","buruh","tki","tkw","deportasi","outsourcing"
]

def cek_spam(text):
    text = str(text).lower()
    for word in promo:
        if re.search(r'\b' + re.escape(word) + r'\b', text):
            return True
    return False

In [ ]:
df_clean = df[~df['full_text'].apply(cek_spam)]
df_clean.reset_index(drop=True, inplace=True)

print("Jumlah data awal:", len(df))
print("Jumlah data setelah hapus promosi:", len(df_clean))

Jumlah data awal: 4465
Jumlah data setelah hapus promosi: 4444

In [ ]:
#hapus link
df_clean = df_clean[~df_clean['full_text'].str.contains("http", case=False)]
#hapus twit pendek
df_clean = df_clean[df_clean['full_text'].str.len() > 10]

In [ ]:
#reset index
df_clean = df_clean.reset_index(drop=True)
df_clean

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1.930000e+18,2025-06-15T13:36:00.000Z,128,Sch! Guys aku ada grup belajar buat angkatan 2...,1.930000e+18,NaN,NaN,in,NaN,1,249,8,https://x.com/schfess/status/1934243496950632754,1.200000e+18,schfess
1,1.930000e+18,2025-06-16T10:01:07.000Z,31,sch! guys aku ada grup belajar buat angkatan 2...,1.930000e+18,NaN,NaN,in,NaN,0,80,0,https://x.com/schfess/status/1934551807960990030,1.200000e+18,schfess
2,1.930000e+18,2025-06-17T00:11:41.000Z,36,Semoga mental ku sebagai akt 26 ini kuat mengh...,1.930000e+18,NaN,NaN,in,NaN,0,2,7,https://x.com/kejaaanaaa/status/19347658565355...,1.770000e+18,kejaaanaaa
3,1.940000e+18,2025-06-17T22:45:05.000Z,0,stud! aku ada rekomendasi grup ambis nih buat ...,1.940000e+18,NaN,NaN,in,NaN,0,0,0,https://x.com/snbtfess/status/1935106452164677866,1.520000e+18,snbtfess
4,1.930000e+18,2025-06-17T05:30:36.000Z,0,Tka kok 9 hari dah kan tesnya 5 doang,1.930000e+18,NaN,NaN,in,NaN,0,2,0,https://x.com/kejaaanaaa/status/19348461166649...,1.770000e+18,kejaaanaaa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4438,1.990000e+18,2025-11-26T10:56:44.000Z,0,besok PAS statistika tapii soal soal tka (gug...,1.990000e+18,NaN,NaN,in,NaN,0,0,0,https://x.com/lovebrawijaya/status/19936350227...,1.780000e+18,lovebrawijaya
4439,1.990000e+18,2025-11-24T09:04:51.000Z,0,abis gladi ASAS dan wow wkwk soal soalnya miri...,1.990000e+18,NaN,NaN,in,NaN,0,1,0,https://x.com/lownJgf/status/1992882092368429528,1.630000e+18,lownJgf
4440,1.990000e+18,2025-11-10T11:39:14.000Z,0,guruku nyuruh nulis kembali 10 soal tka b indo...,1.990000e+18,NaN,NaN,in,NaN,0,0,0,https://x.com/byoviewer/status/198784751563147...,1.490000e+18,byoviewer
4441,2.000000e+18,2025-12-01T12:39:47.000Z,0,UAS bindo ku pake soal tka bejir,2.000000e+18,NaN,NaN,in,NaN,0,0,0,https://x.com/taes_noo/status/1995472899310829824,1.880000e+18,taes_noo
4442,1.990000e+18,2025-11-05T01:35:00.000Z,0,Ada yang punya bocoran soal tka kimia ga? ptn!,1.990000e+18,NaN,NaN,in,NaN,0,1,0,https://x.com/sbmptnfess/status/19858835144963...,1.210000e+18,sbmptnfess

In [ ]:
# Konversi kolom "created_at" ke tipe datetime
df_clean["created_at"] = pd.to_datetime(df["created_at"])
# Mengurutkan data dari yang paling lama ke yang terbaru
df_sorted = df_clean.sort_values(by="created_at", ascending=True)

print(df_sorted[["created_at"]].head())  # 5 data teratas
print(df_sorted[["created_at", "full_text"]].tail(70))  # 5 data terbawah

                    created_at
4078 2025-05-29 09:06:06+00:00
3790 2025-05-29 14:24:07+00:00
4091 2025-05-29 17:17:52+00:00
4054 2025-05-29 18:02:02+00:00
4081 2025-05-30 03:15:56+00:00
                    created_at  \
3461 2025-12-31 17:08:19+00:00
3454 2025-12-31 17:46:01+00:00
3455 2025-12-31 18:00:57+00:00
3476 2026-01-01 03:15:05+00:00
3474 2026-01-01 09:12:14+00:00
...                        ...
3472 2026-01-04 17:05:35+00:00
3485 2026-01-04 17:19:54+00:00
3465 2026-01-04 19:30:24+00:00
3445 2026-01-04 22:32:08+00:00
3468 2026-01-04 23:46:32+00:00

                                              full_text
3461  Aku sakit dari bulan November sampai hari ini ...
3454  annyeonghaseyo ak akn aktif terus smpai mpls n...
3455           sebelum tidur alangkah baiknya vote dulu
3476  gimana kalo buat Free Class untuk persiapan TK...
3474  Social Media should be restricted for those un...
...                                                 ...
3472  Ya allah, h- brp nilai tka d bgiin, bismillah ...
3485  halowww teman" aku mau tanya dong, yang tahun ...
3465                       tbl bsk pengumuman eli n tka
3445                   OI damn 5 January…. Sertif TKA….
3468  Ada yg sampe sekarang belum dikasih nilai TKA ...

[70 rows x 2 columns]

In [ ]:
df_sorted.reset_index(drop=True, inplace=True)

In [ ]:
df_sorted

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1.940000e+18,2025-05-29 09:06:06+00:00,0,YA ALLAH CAPEKBGTT BELAJAR TKA,1.940000e+18,NaN,NaN,in,NaN,0,0,0,https://x.com/heeseungunair/status/19393460528...,1.650000e+18,heeseungunair
1,1.960000e+18,2025-05-29 14:24:07+00:00,2,hiii tmntmn ada yang punya server discord buat...,1.960000e+18,NaN,NaN,in,NaN,0,0,2,https://x.com/parfaither/status/19560070653837...,1.830000e+18,parfaither
2,1.940000e+18,2025-05-29 17:17:52+00:00,0,"Ini kalo file s word gue ilang, gue ngamuk sih...",1.940000e+18,NaN,NaN,in,NaN,1,1,0,https://x.com/amiamourei/status/19393285232122...,1.900000e+18,amiamourei
3,1.930000e+18,2025-05-29 18:02:02+00:00,0,"kalian bljr TKA nya langsung latsol, apa dari ...",1.930000e+18,NaN,NaN,in,NaN,0,1,0,https://x.com/hachiphuw/status/192884612576462...,1.360000e+18,hachiphuw
4,1.940000e+18,2025-05-30 03:15:56+00:00,0,Sekolah macam apa yg sampe hari ini belum shar...,1.940000e+18,NaN,NaN,in,NaN,0,3,0,https://x.com/yunjinrawr/status/19396679593683...,1.510000e+18,yunjinrawr
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4438,2.010000e+18,2026-01-04 17:05:35+00:00,0,"Ya allah, h- brp nilai tka d bgiin, bismillah ...",2.010000e+18,NaN,NaN,in,NaN,0,2,0,https://x.com/lydelta_/status/2007811569472946533,1.750000e+18,lydelta_
4439,2.010000e+18,2026-01-04 17:19:54+00:00,1,"halowww teman"" aku mau tanya dong, yang tahun ...",2.010000e+18,NaN,NaN,in,NaN,0,0,0,https://x.com/ayymakinambis/status/20068885146...,1.800000e+18,ayymakinambis
4440,2.010000e+18,2026-01-04 19:30:24+00:00,0,tbl bsk pengumuman eli n tka,2.010000e+18,NaN,NaN,in,NaN,0,0,0,https://x.com/jwiethinker/status/2007864576797...,1.310000e+18,jwiethinker
4441,2.010000e+18,2026-01-04 22:32:08+00:00,1,OI damn 5 January…. Sertif TKA….,2.010000e+18,NaN,NaN,in,NaN,0,4,0,https://x.com/aeromies/status/2007897421641379862,1.680000e+18,aeromies
4442,2.010000e+18,2026-01-04 23:46:32+00:00,1,Ada yg sampe sekarang belum dikasih nilai TKA ...,2.010000e+18,NaN,NaN,in,NaN,0,0,0,https://x.com/nanadindaa/status/20078236734499...,1.930000e+18,nanadindaa

In [ ]:
df_sorted.to_csv("dataset_final.csv", index=False)